### ISSUE TITLE
EIP1 invalid domain VPC

### ISSUE THREAD

**Issue by davidroush** [PaloAltoNetworks/aws-elb-autoscaling#3]
Encountered an error deploying the alb template, the uppercase "VPC" in each EIP section was throwing an error. To correct this, change the "Domain" value to lowercase in each EIP definition:

    "EIP1" : {
       "Type" : "AWS::EC2::EIP",
       "Condition" : "NATGatewayRequired",
       "Properties" : {
          "Domain" : "vpc"

**Comment by narayan-pan** [comment]
Hi David,
   We have never encountered this error internally. Just relaunched this am w/o your change and everything worked fine. Do you happen to have a screen grab of the error?
