### ISSUE TITLE
LambdaCustomResource create fails

### ISSUE THREAD

**Issue by toddrosner** [PaloAltoNetworks/aws-elb-autoscaling#4]
Just testing the templates out. Seems that no matter which template I use, or which AMI I use, i.e. BYOL or PAYG, I get the same error which results in rollback.

`08:20:14 UTC-0700	CREATE_FAILED	AWS::CloudFormation::Stack	vpc-alb-v12-az3n-1FYGH9LY5ZA7	The following resource(s) failed to create: [LambdaCustomResource].`
`08:20:13 UTC-0700	CREATE_FAILED	AWS::CloudFormation::CustomResource	LambdaCustomResource	Invalid Response object: 'FAILURE' is not a valid ResponseStatus`

The deployment is happening in us-west-2 where Lambda exists.

**Comment by narayan-iyengar** [comment]
Can you check the Cloudwatch logs for the InitLambda function for that deploymen?
This can be due to several reasons: no EIPs available (or not enough) for instance.

The deployment guide has a troubleshooting section that walks you through where to look.

**Comment by toddrosner** [comment]
Thanks @narayan-iyengar 

So it turns out the problem was that the stack name I was using had 11 characters which is unsupported...

```
[ERROR]	2017-06-18T00:44:45.812Z	52238dc7-53bf-11e7-a81f-394187e2ffca	[ERROR]: We dont support Stack Name more than 10 characters long...
```
Would be a good idea to add a comment beside the `Stack name` field to inform that there's a 10 character maximum.

**Comment by narayan-iyengar** [comment]
Closing the issue
